const fs = require('fs');
const path = require('path');

/**
 * Generates multiple Mermaid-based data flow diagram pages
 * Split into digestible chunks with zoom/pan support
 */
function generateMermaidFlows(data, outputDir, getSharedStyles, getSidebar) {
  const flows = [
    { id: 'auth', name: 'Authentication Flow', icon: '🔐', generator: generateAuthFlow },
    { id: 'payment', name: 'Payment Flow', icon: '💳', generator: generatePaymentFlow },
    { id: 'data', name: 'Data Flow', icon: '📊', generator: generateDataFlow },
    { id: 'storage', name: 'Storage Flow', icon: '💾', generator: generateStorageFlow },
    { id: 'api', name: 'API Overview', icon: '🔌', generator: generateApiOverview },
    { id: 'deployment', name: 'Deployment Flow', icon: '🚀', generator: generateDeploymentFlow, multiDiagram: true },
    { id: 'architecture', name: 'Architecture Overview', icon: '🏗️', generator: generateArchitectureOverview, multiDiagram: true },
    { id: 'security', name: 'Security Audit', icon: '🔒', generator: generateSecurityAudit },
    { id: 'onboarding', name: 'Onboarding Flow', icon: '📚', generator: generateOnboardingFlow, multiDiagram: true },
  ];

  // Generate index page for all flows
  const indexHTML = generateFlowIndex(data, flows, getSharedStyles, getSidebar);
  fs.writeFileSync(path.join(outputDir, 'data-flow.html'), indexHTML);

  // Generate individual flow pages
  flows.forEach(flow => {
    const html = generateFlowPage(data, flow, flows, getSharedStyles, getSidebar);
    fs.writeFileSync(path.join(outputDir, `flow-${flow.id}.html`), html);
  });

  return flows;
}

function generateFlowIndex(data, flows, getSharedStyles, getSidebar) {
  const flowCardsHTML = flows.map(flow => `
    <a href="flow-${flow.id}.html" class="flow-card">
      <div class="flow-card-icon">${flow.icon}</div>
      <div class="flow-card-content">
        <h3>${flow.name}</h3>
        <p>${getFlowDescription(flow.id)}</p>
      </div>
      <div class="flow-card-arrow">→</div>
    </a>
  `).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${data.projectTitle} - Data Flow Diagrams</title>
  <style>
    ${getSharedStyles()}
    .flow-cards { display: flex; flex-direction: column; gap: 16px; max-width: 700px; }
    .flow-card { display: flex; align-items: center; gap: 20px; padding: 24px; background: var(--bg-card); border: 1px solid var(--border); border-radius: 16px; text-decoration: none; color: inherit; transition: all 0.2s; }
    .flow-card:hover { border-color: var(--accent); background: var(--bg-hover); transform: translateX(4px); }
    .flow-card-icon { font-size: 32px; width: 60px; height: 60px; display: flex; align-items: center; justify-content: center; background: var(--accent-dim); border-radius: 12px; }
    .flow-card-content { flex: 1; }
    .flow-card-content h3 { font-size: 18px; margin-bottom: 4px; }
    .flow-card-content p { color: var(--text-muted); font-size: 14px; }
    .flow-card-arrow { font-size: 24px; color: var(--accent); opacity: 0; transition: opacity 0.2s; }
    .flow-card:hover .flow-card-arrow { opacity: 1; }
    .intro-box { background: linear-gradient(135deg, rgba(6,182,212,0.15), rgba(99,102,241,0.15)); border: 1px solid rgba(6,182,212,0.3); border-radius: 16px; padding: 24px; margin-bottom: 32px; }
    .intro-box h2 { color: #67e8f9; margin-bottom: 8px; font-size: 16px; }
    .intro-box p { color: var(--text-muted); font-size: 14px; line-height: 1.6; }
  </style>
</head>
<body>
  <div class="layout">
    ${getSidebar(data, 'dataflow')}
    <main class="main">
      <h1>Data Flow Diagrams</h1>
      <p class="desc">Interactive Mermaid diagrams showing how data moves through the application. Each flow is broken into digestible sections.</p>

      <div class="intro-box">
        <h2>How to Read These Diagrams</h2>
        <p>Each diagram shows the flow of data through different parts of the system. Boxes represent components or services, arrows show data movement, and colors indicate different types of operations (auth, storage, external services, etc.).</p>
      </div>

      <div class="flow-cards">
        ${flowCardsHTML}
      </div>

      <p style="text-align: center; margin-top: 48px; color: #71717a; font-size: 12px;">Generated by on-bored &bull; ${new Date().toLocaleDateString()}</p>
    </main>
  </div>
</body>
</html>`;
}

function generateFlowPage(data, flow, allFlows, getSharedStyles, getSidebar) {
  const mermaidResult = flow.generator(data);
  const description = getFlowDescription(flow.id);

  // Handle multi-diagram flows
  const diagrams = flow.multiDiagram ? mermaidResult : [{ title: flow.name, code: mermaidResult }];

  // Generate nav tabs for all flows
  const navTabsHTML = allFlows.map(f => `
    <a href="flow-${f.id}.html" class="flow-tab ${f.id === flow.id ? 'active' : ''}">
      <span class="tab-icon">${f.icon}</span>
      <span class="tab-label">${f.name.replace(' Flow', '').replace(' Overview', '')}</span>
    </a>
  `).join('\n');

  // Generate diagram sections
  const diagramsHTML = diagrams.map((diagram, idx) => `
    <div class="diagram-section" id="diagram-${idx}">
      ${flow.multiDiagram ? `<h2 class="diagram-title">${diagram.title}</h2>` : ''}
      ${diagram.description ? `<p class="diagram-desc">${diagram.description}</p>` : ''}
      <div class="mermaid-container">
        <div class="zoom-controls">
          <button onclick="zoomIn(${idx})" title="Zoom In">+</button>
          <button onclick="zoomOut(${idx})" title="Zoom Out">−</button>
          <button onclick="resetZoom(${idx})" title="Reset">↺</button>
          <button onclick="toggleFullscreen(${idx})" title="Fullscreen">⛶</button>
          <button onclick="toggleCode(${idx})">Code</button>
        </div>
        <div class="mermaid-wrapper" id="mermaid-wrapper-${idx}">
          <div class="mermaid" id="mermaid-${idx}">
${diagram.code}
          </div>
        </div>
        <pre class="mermaid-code" id="mermaid-code-${idx}">${escapeHtml(diagram.code)}</pre>
      </div>
    </div>
  `).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${data.projectTitle} - ${flow.name}</title>
  <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/svg-pan-zoom@3.6.1/dist/svg-pan-zoom.min.js"></script>
  <style>
    ${getSharedStyles()}
    .flow-tabs { display: flex; gap: 8px; margin-bottom: 24px; flex-wrap: wrap; }
    .flow-tab { display: flex; align-items: center; gap: 8px; padding: 10px 16px; background: var(--bg-card); border: 1px solid var(--border); border-radius: 10px; text-decoration: none; color: var(--text-muted); font-size: 13px; transition: all 0.2s; }
    .flow-tab:hover { border-color: var(--accent); color: var(--text); }
    .flow-tab.active { background: var(--accent); border-color: var(--accent); color: white; }
    .tab-icon { font-size: 16px; }
    .diagram-section { margin-bottom: 40px; }
    .diagram-title { font-size: 20px; margin-bottom: 8px; color: var(--accent-light); }
    .diagram-desc { color: var(--text-muted); font-size: 14px; margin-bottom: 16px; }
    .mermaid-container { background: var(--bg-card); border: 1px solid var(--border); border-radius: 16px; padding: 20px; margin-bottom: 24px; position: relative; }
    .mermaid-wrapper { overflow: hidden; min-height: 400px; cursor: grab; border-radius: 8px; background: var(--bg); }
    .mermaid-wrapper:active { cursor: grabbing; }
    .mermaid-wrapper.fullscreen { position: fixed; top: 0; left: 0; right: 0; bottom: 0; z-index: 9999; background: var(--bg); min-height: 100vh; border-radius: 0; }
    .mermaid { display: flex; justify-content: center; padding: 20px; }
    .mermaid svg { max-width: none !important; height: auto; }
    .zoom-controls { display: flex; gap: 8px; margin-bottom: 12px; justify-content: flex-end; flex-wrap: wrap; }
    .zoom-controls button { padding: 8px 14px; background: var(--bg-hover); border: 1px solid var(--border); border-radius: 6px; color: var(--text-muted); font-size: 14px; cursor: pointer; transition: all 0.2s; }
    .zoom-controls button:hover { color: var(--text); border-color: var(--accent); background: var(--accent-dim); }
    .flow-description { background: var(--bg-card); border: 1px solid var(--border); border-radius: 12px; padding: 20px; margin-bottom: 24px; }
    .flow-description h3 { font-size: 14px; color: var(--accent); margin-bottom: 8px; }
    .flow-description p { color: var(--text-muted); font-size: 14px; line-height: 1.6; }
    .mermaid-code { display: none; background: #0d0d0f; border: 1px solid var(--border); border-radius: 8px; padding: 16px; font-family: 'SF Mono', Monaco, monospace; font-size: 12px; line-height: 1.5; white-space: pre; overflow-x: auto; color: #a5b4fc; margin-top: 16px; max-height: 300px; }
    .mermaid-code.visible { display: block; }
    .legend { display: flex; flex-wrap: wrap; gap: 16px; padding: 16px; background: var(--bg-hover); border-radius: 8px; margin-top: 16px; }
    .legend-item { display: flex; align-items: center; gap: 8px; font-size: 12px; color: var(--text-muted); }
    .legend-color { width: 16px; height: 16px; border-radius: 4px; }
    .back-link { display: inline-flex; align-items: center; gap: 8px; color: var(--accent); text-decoration: none; font-size: 14px; margin-bottom: 24px; }
    .back-link:hover { text-decoration: underline; }
    .zoom-hint { text-align: center; color: var(--text-muted); font-size: 12px; margin-top: 8px; }
  </style>
</head>
<body>
  <div class="layout">
    ${getSidebar(data, 'dataflow')}
    <main class="main">
      <a href="data-flow.html" class="back-link">← All Flow Diagrams</a>

      <h1>${flow.icon} ${flow.name}</h1>
      <p class="desc">${description}</p>

      <div class="flow-tabs">
        ${navTabsHTML}
      </div>

      <div class="flow-description">
        <h3>What This Diagram Shows</h3>
        <p>${getDetailedDescription(flow.id)}</p>
      </div>

      ${diagramsHTML}

      <div class="legend">
        ${getLegendItems(flow.id)}
      </div>

      <p class="zoom-hint">💡 Use mouse wheel to zoom, drag to pan. Click ⛶ for fullscreen.</p>

      <p style="text-align: center; margin-top: 48px; color: #71717a; font-size: 12px;">Generated by on-bored &bull; ${new Date().toLocaleDateString()}</p>
    </main>
  </div>

  <script>
    const panZoomInstances = {};

    mermaid.initialize({
      startOnLoad: true,
      theme: 'dark',
      themeVariables: {
        primaryColor: '#6366f1',
        primaryTextColor: '#fafafa',
        primaryBorderColor: '#27272a',
        lineColor: '#71717a',
        secondaryColor: '#22c55e',
        tertiaryColor: '#12121a',
        background: '#12121a',
        mainBkg: '#1a1a24',
        nodeBorder: '#27272a',
        clusterBkg: '#12121a',
        clusterBorder: '#27272a',
        titleColor: '#fafafa',
        edgeLabelBackground: '#1a1a24'
      },
      flowchart: {
        useMaxWidth: false,
        htmlLabels: true,
        curve: 'basis'
      },
      sequence: {
        useMaxWidth: false
      }
    });

    // Initialize pan-zoom after mermaid renders
    setTimeout(() => {
      document.querySelectorAll('.mermaid svg').forEach((svg, idx) => {
        try {
          panZoomInstances[idx] = svgPanZoom(svg, {
            zoomEnabled: true,
            controlIconsEnabled: false,
            fit: true,
            center: true,
            minZoom: 0.1,
            maxZoom: 10,
            zoomScaleSensitivity: 0.3
          });
        } catch(e) { console.log('Pan-zoom init error:', e); }
      });
    }, 500);

    function zoomIn(idx) {
      if (panZoomInstances[idx]) panZoomInstances[idx].zoomIn();
    }

    function zoomOut(idx) {
      if (panZoomInstances[idx]) panZoomInstances[idx].zoomOut();
    }

    function resetZoom(idx) {
      if (panZoomInstances[idx]) {
        panZoomInstances[idx].resetZoom();
        panZoomInstances[idx].center();
      }
    }

    function toggleFullscreen(idx) {
      const wrapper = document.getElementById('mermaid-wrapper-' + idx);
      wrapper.classList.toggle('fullscreen');
      setTimeout(() => {
        if (panZoomInstances[idx]) {
          panZoomInstances[idx].resize();
          panZoomInstances[idx].fit();
          panZoomInstances[idx].center();
        }
      }, 100);
    }

    function toggleCode(idx) {
      const codeEl = document.getElementById('mermaid-code-' + idx);
      codeEl.classList.toggle('visible');
    }

    // ESC to exit fullscreen
    document.addEventListener('keydown', (e) => {
      if (e.key === 'Escape') {
        document.querySelectorAll('.mermaid-wrapper.fullscreen').forEach(el => {
          el.classList.remove('fullscreen');
        });
      }
    });
  </script>
</body>
</html>`;
}

// ============ FLOW GENERATORS ============

function generateAuthFlow(data) {
  return `flowchart TD
    subgraph Client["Client Browser"]
        A[User] --> B{Login Method}
        B -->|Email/Password| C[Login Form]
        B -->|Token| D[Token Login]
    end

    subgraph Auth["Appwrite Auth SDK"]
        C --> F["/api/auth/login"]
        D --> G["/api/auth/token-login"]
        F --> I{Appwrite.createEmailPasswordSession}
        G --> I
    end

    subgraph Session["Session Storage"]
        I -->|Valid| J[Appwrite Session Token]
        I -->|Invalid| K[Return 401 Error]
        J --> L["HttpOnly Cookie: a_session_xxx"]
        J --> M["localStorage: staryo-auth-session"]
        J --> N[Build Permissions Object]
    end

    subgraph TwoFA["2FA - Appwrite Functions"]
        I -->|2FA Required| O{2FA Method}
        O -->|TOTP| P["Appwrite TOTP /api/auth/totp/verify"]
        O -->|Email| Q["Appwrite Email /api/auth/2fa/verify-email"]
        O -->|SMS| R["Appwrite Phone /api/auth/2fa/verify-phone"]
        P --> J
        Q --> J
        R --> J
    end

    subgraph AgeVerify["SumSub Age Verification"]
        AA[Creator Application] --> AB["/api/sumsub/access-token"]
        AB --> AC["SumSub WebSDK Document Upload"]
        AC --> AD["SumSub API ID Verification"]
        AD --> AE["Webhook Callback Verified/Rejected"]
        AE --> AF[Update User Labels]
    end

    subgraph Verify["Request Middleware"]
        S[Every HTTP Request] --> T["middleware.ts Astro"]
        T --> U["Read Cookie a_session_xxx"]
        U --> V{Appwrite.getAccount}
        V -->|Valid| W["Attach to Astro.locals user, permissions"]
        V -->|Invalid| X[Clear All Sessions]
        X --> Y[Redirect /login]
    end

    N --> S

    classDef client fill:#3b82f6,stroke:#1d4ed8,color:#fff
    classDef auth fill:#6366f1,stroke:#4f46e5,color:#fff
    classDef session fill:#22c55e,stroke:#15803d,color:#fff
    classDef twofa fill:#f97316,stroke:#c2410c,color:#fff
    classDef verify fill:#06b6d4,stroke:#0891b2,color:#fff
    classDef sumsub fill:#ec4899,stroke:#be185d,color:#fff
    classDef error fill:#ef4444,stroke:#b91c1c,color:#fff

    class A,B,C,D client
    class F,G,I auth
    class J,L,M,N session
    class O,P,Q,R twofa
    class S,T,U,V,W verify
    class AA,AB,AC,AD,AE,AF sumsub
    class K,X,Y error`;
}

function generatePaymentFlow(data) {
  return `flowchart TD
    subgraph User["User Actions"]
        A[User] --> B["Select Star Package StarPackagesModal.vue"]
        B --> C[Click Purchase]
    end

    subgraph Checkout["Checkout Creation"]
        C --> D["/api/stripe/create-checkout"]
        D --> E{Validation Steps}
        E -->|1| F["Appwrite getAccount Verify Auth"]
        E -->|2| G["Query STAR_PACKAGES Validate Package"]
        E -->|3| H["Query TRANSACTIONS Check Value Pack Bonus"]
        F & G & H --> I["Stripe.checkout.sessions.create Embedded Mode"]
    end

    subgraph Stripe["Stripe Checkout"]
        I --> J["Stripe Embedded Checkout @stripe/stripe-js"]
        J --> K{Payment Result}
        K -->|Success| L["checkout.session.completed Event"]
        K -->|Failed| M[Show Stripe Error]
        K -->|Cancelled| N[Return to App]
    end

    subgraph Fulfillment["Order Fulfillment"]
        L --> O["/api/stripe/process-return"]
        O --> P{"stripe.webhooks.constructEvent()"}
        P -->|Signature Valid| Q["StarBalanceService.creditUserStars()"]
        P -->|Invalid| R[Log and Reject 400]
        Q --> S["Create STAR_TRANSACTIONS Appwrite"]
        S --> T["Update STAR_BALANCE Appwrite"]
        T --> U["Redirect /purchase/success?stars=amount"]
    end

    subgraph Payout["Stripe Connect - Creator Payouts"]
        V[Creator Cash Out] --> W["/api/stripe/connect/onboard"]
        W --> X["Stripe.accounts.create type: express"]
        X --> Y["Store in STRIPE_ACCOUNTS Appwrite"]
        Y --> Z["/api/stripe/connect/payout"]
        Z --> AA["Stripe.transfers.create to Creator Bank"]
    end

    subgraph Database["Appwrite Collections"]
        DB1[(STAR_PACKAGES)]
        DB2[(STAR_BALANCE)]
        DB3[(STAR_TRANSACTIONS)]
        DB4[(STRIPE_ACCOUNTS)]
    end

    G -.-> DB1
    T -.-> DB2
    S -.-> DB3
    Y -.-> DB4

    classDef user fill:#3b82f6,stroke:#1d4ed8,color:#fff
    classDef checkout fill:#6366f1,stroke:#4f46e5,color:#fff
    classDef stripe fill:#635bff,stroke:#4f46e5,color:#fff
    classDef fulfillment fill:#22c55e,stroke:#15803d,color:#fff
    classDef payout fill:#f97316,stroke:#c2410c,color:#fff
    classDef database fill:#1a1a24,stroke:#27272a,color:#a1a1aa
    classDef error fill:#ef4444,stroke:#b91c1c,color:#fff

    class A,B,C user
    class D,E,F,G,H,I checkout
    class J,K stripe
    class L,O,P,Q,S,T,U fulfillment
    class V,W,X,Y,Z,AA payout
    class DB1,DB2,DB3,DB4 database
    class M,N,R error`;
}

function generateDataFlow(data) {
  return `flowchart TD
    subgraph Input["Vue Components"]
        A[User] --> B{Content Type}
        B -->|Text| C["MessageInput.vue"]
        B -->|Media| D["MediaPickerFloating.vue"]
        B -->|Gift| E["GiftSelector.vue"]
    end

    subgraph Safety["SafetyService.ts"]
        C --> F["/api/security/check-message"]
        D --> G["/api/safety/process-video-smart"]
        F --> H{SafetyService.checkContent}
        G --> H
        H -->|Text| I["Groq LlamaGuard 4 llama-guard-4-8b"]
        H -->|Video| J["Canvas API Frame Extraction"]
        H -->|Audio| JA["Groq Whisper whisper-large-v3-turbo"]
        J --> JB["Groq Vision API Frame Analysis"]
        H -->|Image| K["pHash MediaProcessorClient"]
        I & JB & K --> L{Violation Categories}
        L -->|S1-S4| N["Block Message Policy Violation"]
    end

    subgraph Processing["/api/messages/send.json.ts"]
        L -->|Safe| M[PaymentService]
        M --> O{Payment Type}
        O -->|Free| P["USER_SETTINGS freeMessagesUsed++"]
        O -->|Custom| PA["CUSTOM_CURRENCY Deduct Creator Currency"]
        O -->|Stars| Q["StarBalanceService.deductStars FIFO"]
        Q --> R["STAR_TRANSACTIONS Appwrite SDK"]
        P & PA & R --> S["MESSAGES Appwrite SDK"]
    end

    subgraph Storage["Appwrite Database"]
        S --> T[("MESSAGES text, mediaId, metadata")]
        S --> U[("CONVERSATIONS lastMessage, participants")]
        D --> V[("Storage Bucket userId encrypted")]
        R --> W[("STAR_TRANSACTIONS amount, type, status")]
        H -.-> WA[("VERIFIED_CONTENT pHash, safetyScore")]
    end

    subgraph Delivery["Appwrite Realtime"]
        T --> X["WebSocket documents.*.create"]
        X --> Y["useMessages.ts Vue Composable"]
        Y --> Z["Appwrite Functions Push Notification"]
    end

    classDef input fill:#3b82f6,stroke:#1d4ed8,color:#fff
    classDef safety fill:#f97316,stroke:#c2410c,color:#fff
    classDef processing fill:#6366f1,stroke:#4f46e5,color:#fff
    classDef storage fill:#22c55e,stroke:#15803d,color:#fff
    classDef delivery fill:#06b6d4,stroke:#0891b2,color:#fff
    classDef blocked fill:#ef4444,stroke:#b91c1c,color:#fff

    class A,B,C,D,E input
    class F,G,H,I,J,JA,JB,K,L safety
    class M,O,P,PA,Q,R,S processing
    class T,U,V,W,WA storage
    class X,Y,Z delivery
    class N blocked`;
}

function generateStorageFlow(data) {
  return `flowchart TD
    subgraph Upload["/api/media/create.json.ts"]
        A[User] --> B["MediaPickerFloating.vue File Selection"]
        B --> C{File Format}
        C -->|HEIC| CA["heic-convert to JPEG"]
        C -->|Other| CB[Pass Through]
        CA & CB --> D{File Type}
        D -->|Image| E[Image Pipeline]
        D -->|Video| F[Video Pipeline]
        D -->|Audio| G[Audio Pipeline]
    end

    subgraph Processing["MediaProcessorClient.ts"]
        E --> H["Canvas API Thumbnail Gen"]
        E --> I["pHash Algorithm Perceptual Hash"]
        F --> J["Canvas API Smart Frame Extraction"]
        F --> K["FFmpeg.wasm Transcode - planned"]
        G --> L["Groq Whisper whisper-large-v3-turbo"]
        H & I --> M["Groq LlamaGuard 4 Safety Classification"]
        J --> M
        L --> M
    end

    subgraph Buckets["Appwrite Storage Buckets"]
        M --> N{StorageService.ts}
        N -->|Avatar| O[("profile_pictures Public Read")]
        N -->|Shared| P[("media Auth Required")]
        N -->|Private| Q[("Bucket: userId Owner Only")]
        N -->|Assets| R[("gifts_star_packages Public Read")]
    end

    subgraph Security["Appwrite Storage Config"]
        O & P & Q & R --> S["Appwrite SDK storage.createFile"]
        S --> T["AES-256 Encryption At Rest"]
        S --> U["ClamAV Antivirus On Upload"]
        S --> V["Gzip Compression Automatic"]
        S --> VA["Max 1GB Per File"]
    end

    subgraph Access["/api/media/bucketId/fileId.ts"]
        W[Download Request] --> X["Appwrite SDK storage.getFileDownload"]
        X --> Y{Permission.read Check}
        Y -->|Role.user| Z[Stream File]
        Y -->|Role.team| Z
        Y -->|Role.any| Z
        Y -->|Denied| AA[HTTP 403]
    end

    subgraph Caching["HTTP Caching"]
        Z --> AB["ETag Header bucketId-fileId"]
        AB --> AC["Cache-Control max-age=86400"]
        AC --> AD["Cloudflare CDN Edge Cache"]
    end

    classDef upload fill:#3b82f6,stroke:#1d4ed8,color:#fff
    classDef processing fill:#6366f1,stroke:#4f46e5,color:#fff
    classDef buckets fill:#22c55e,stroke:#15803d,color:#fff
    classDef security fill:#f97316,stroke:#c2410c,color:#fff
    classDef access fill:#06b6d4,stroke:#0891b2,color:#fff
    classDef caching fill:#ec4899,stroke:#be185d,color:#fff
    classDef error fill:#ef4444,stroke:#b91c1c,color:#fff

    class A,B,C,CA,CB,D upload
    class E,F,G,H,I,J,K,L,M processing
    class N,O,P,Q,R buckets
    class S,T,U,V,VA security
    class W,X,Y,Z access
    class AB,AC,AD caching
    class AA error`;
}

function generateApiOverview(data) {
  return `flowchart LR
    subgraph Client["Client"]
        A[Web App]
        B[Mobile App]
    end

    subgraph Gateway["API Gateway"]
        C[Request Handler]
        D[Auth Middleware]
        E[Rate Limiter]
    end

    A & B --> C
    C --> D --> E

    subgraph Auth["Auth APIs"]
        F1["/api/auth/login"]
        F2["/api/auth/verify"]
        F3["/api/auth/token-login"]
        F4["/api/auth/2fa/verify-*"]
    end

    subgraph Payment["Payment APIs"]
        G1["/api/stripe/create-checkout"]
        G2["/api/stripe/process-return"]
        G3["/api/stripe/connect/onboard"]
        G4["/api/stripe/connect/payout"]
        G5["/api/stripe/connect/balance"]
    end

    subgraph Message["Message APIs"]
        H1["/api/messages/send"]
        H2["/api/security/check-message"]
    end

    subgraph Media["Media APIs"]
        I1["/api/media/create"]
        I2["/api/media/process"]
        I3["/api/media/bucketId/fileId"]
        I4["/api/safety/process-video-smart"]
    end

    subgraph Admin["Admin APIs"]
        J1["/api/admin/*"]
        J2["/api/settings/deletion-*"]
    end

    E --> Auth & Payment & Message & Media & Admin

    subgraph Backend["Backend Services"]
        L[("Appwrite Cloud nyc.cloud.appwrite.io")]
        M[("Appwrite Storage AES-256 + ClamAV")]
        N["Stripe API Checkout + Connect"]
        O["Groq API LlamaGuard + Whisper"]
        OA["SumSub API Age Verification"]
    end

    Auth & Payment & Message & Media & Admin --> L
    Auth --> OA
    Media --> M
    Payment --> N
    Message --> O

    subgraph Tools["Processing Tools"]
        T1["pHash Image Hashing"]
        T2["Canvas API Frame Extract"]
        T3["heic-convert HEIC to JPEG"]
        T4["FFmpeg.wasm Video - planned"]
    end

    Media --> T1 & T2 & T3 & T4

    classDef client fill:#3b82f6,stroke:#1d4ed8,color:#fff
    classDef gateway fill:#71717a,stroke:#52525b,color:#fff
    classDef auth fill:#6366f1,stroke:#4f46e5,color:#fff
    classDef payment fill:#22c55e,stroke:#15803d,color:#fff
    classDef message fill:#06b6d4,stroke:#0891b2,color:#fff
    classDef media fill:#f97316,stroke:#c2410c,color:#fff
    classDef admin fill:#ef4444,stroke:#b91c1c,color:#fff
    classDef backend fill:#1a1a24,stroke:#27272a,color:#fafafa
    classDef tools fill:#12121a,stroke:#27272a,color:#a1a1aa

    class A,B client
    class C,D,E gateway
    class L,M,N,O,OA backend
    class T1,T2,T3,T4 tools`;
}

// ============ NEW FLOW GENERATORS ============

function generateDeploymentFlow(data) {
  return [
    {
      title: 'Deployment Pipeline',
      description: 'Build, deploy, and infrastructure architecture for Cloudflare Workers.',
      code: `flowchart TD
    subgraph Development["Local Development"]
        A[Developer] --> B["pnpm dev"]
        B --> C["Astro Dev Server :4444"]
        C --> D["Vite HMR"]
        D --> E["Vue Islands Hydration"]
    end

    subgraph Build["Build Process"]
        F["pnpm build"] --> G["Astro Check TypeScript"]
        G --> H["Vite Build"]
        H --> I["@astrojs/cloudflare Adapter"]
        I --> J["dist/_worker.js/index.js"]
        I --> K["dist/ Static Assets"]
        H --> L["removeConsole Plugin"]
        H --> M["@playform/compress Gzip/Brotli"]
    end

    subgraph Deploy["Cloudflare Deployment"]
        J --> N["Wrangler Deploy"]
        K --> N
        N --> O["Cloudflare Workers"]
        N --> P["Cloudflare CDN"]
    end

    subgraph Runtime["Production Runtime"]
        Q[User Request] --> R{"Cloudflare Edge"}
        R -->|Static| P
        R -->|Dynamic| O
        O --> S["KV Storage STARYO-staryo"]
        O --> T["Workers Environment Secrets"]
        P --> U["Edge Cache 86400s"]
    end

    subgraph Backend["Backend Services"]
        O --> V[("Appwrite Cloud nyc.cloud.appwrite.io")]
        O --> W["Stripe API"]
        O --> X["Groq API"]
        O --> Y["SumSub API"]
    end

    subgraph Monitoring["Observability"]
        O --> Z["Cloudflare Logs enabled"]
        O --> ZA["OpenReplay Session Replay"]
    end

    classDef dev fill:#3b82f6,stroke:#1d4ed8,color:#fff
    classDef build fill:#6366f1,stroke:#4f46e5,color:#fff
    classDef deploy fill:#22c55e,stroke:#15803d,color:#fff
    classDef runtime fill:#f97316,stroke:#c2410c,color:#fff
    classDef backend fill:#06b6d4,stroke:#0891b2,color:#fff
    classDef monitor fill:#ec4899,stroke:#be185d,color:#fff

    class A,B,C,D,E dev
    class F,G,H,I,J,K,L,M build
    class N,O,P deploy
    class Q,R,S,T,U runtime
    class V,W,X,Y backend
    class Z,ZA monitor`
    },
    {
      title: 'Build Pipeline',
      description: 'Source files flow through Vite plugins and Astro integrations to produce deployable output.',
      code: `flowchart LR
    subgraph Input["Source Files"]
        A1[".astro Pages"]
        A2[".vue Components"]
        A3[".ts Services"]
        A4[".css Styles"]
    end

    subgraph Vite["Vite Plugins"]
        B1["tsConfigPaths"]
        B2["removeConsole"]
        B3["tailwindcss"]
    end

    subgraph Astro["Astro Integrations"]
        C1["@astrojs/vue"]
        C2["@zachhandley/ez-i18n"]
        C3["@playform/compress"]
        C4["@astrojs/sitemap"]
    end

    subgraph Output["Build Output"]
        D1["_worker.js Worker Entry"]
        D2["_astro/ Hashed Assets"]
        D3["*.html Pre-rendered Pages"]
        D4["sitemap.xml"]
    end

    A1 & A2 & A3 & A4 --> B1 & B2 & B3
    B1 & B2 & B3 --> C1 & C2 & C3 & C4
    C1 & C2 & C3 & C4 --> D1 & D2 & D3 & D4

    classDef input fill:#3b82f6,stroke:#1d4ed8,color:#fff
    classDef vite fill:#6366f1,stroke:#4f46e5,color:#fff
    classDef astro fill:#22c55e,stroke:#15803d,color:#fff
    classDef output fill:#f97316,stroke:#c2410c,color:#fff

    class A1,A2,A3,A4 input
    class B1,B2,B3 vite
    class C1,C2,C3,C4 astro
    class D1,D2,D3,D4 output`
    },
    {
      title: 'Infrastructure Architecture',
      description: 'Global edge network with centralized backend services in NYC.',
      code: `flowchart TB
    subgraph Users["Global Users"]
        U1["Americas"]
        U2["Europe"]
        U3["Asia"]
    end

    subgraph Edge["Cloudflare Edge Network"]
        E1["Edge PoP Americas"]
        E2["Edge PoP Europe"]
        E3["Edge PoP Asia"]
    end

    subgraph Core["Core Infrastructure"]
        CF["Cloudflare Workers staryo"]
        KV["KV Storage Sessions"]
        CDN["CDN Static Assets"]
    end

    subgraph Backend["Backend NYC"]
        AW[("Appwrite Cloud Database/Auth/Storage")]
    end

    subgraph External["External APIs"]
        ST["Stripe Payments"]
        GQ["Groq AI"]
        SS["SumSub KYC"]
    end

    U1 --> E1
    U2 --> E2
    U3 --> E3

    E1 & E2 & E3 --> CF
    E1 & E2 & E3 --> CDN

    CF --> KV
    CF --> AW
    CF --> ST & GQ & SS

    classDef users fill:#3b82f6,stroke:#1d4ed8,color:#fff
    classDef edge fill:#f97316,stroke:#c2410c,color:#fff
    classDef core fill:#6366f1,stroke:#4f46e5,color:#fff
    classDef backend fill:#22c55e,stroke:#15803d,color:#fff
    classDef external fill:#06b6d4,stroke:#0891b2,color:#fff

    class U1,U2,U3 users
    class E1,E2,E3 edge
    class CF,KV,CDN core
    class AW backend
    class ST,GQ,SS external`
    }
  ];
}

function generateArchitectureOverview(data) {
  return [
    {
      title: 'High-Level System Architecture',
      description: 'Complete system architecture showing user types, edge layer, application layer, services, and backend.',
      code: `flowchart TB
    subgraph Users["User Types"]
        U1["Fans"]
        U2["Creators"]
        U3["Agencies"]
        U4["Admins"]
    end

    subgraph Edge["Cloudflare Edge"]
        CF["Workers Runtime"]
        KV["KV Storage"]
        CDN["CDN Assets"]
    end

    subgraph App["Application Layer"]
        ASTRO["Astro SSR"]
        VUE["Vue Islands"]
        API["API Routes /api/*"]
    end

    subgraph Services["Service Layer"]
        AUTH["Auth Service"]
        PAY["Payment Service"]
        MSG["Messaging Service"]
        MEDIA["Media Service"]
        SAFETY["Safety Service"]
    end

    subgraph Backend["Appwrite Cloud NYC"]
        DB[("Database")]
        STOR[("Storage")]
        FUNC["Functions"]
        RT["Realtime WS"]
    end

    subgraph External["External Services"]
        STRIPE["Stripe"]
        GROQ["Groq AI"]
        SUMSUB["SumSub KYC"]
    end

    U1 & U2 & U3 & U4 --> Edge
    Edge --> App
    App --> Services
    Services --> Backend
    Services --> External

    classDef users fill:#3b82f6,stroke:#1d4ed8,color:#fff
    classDef edge fill:#f97316,stroke:#c2410c,color:#fff
    classDef app fill:#6366f1,stroke:#4f46e5,color:#fff
    classDef services fill:#22c55e,stroke:#15803d,color:#fff
    classDef backend fill:#06b6d4,stroke:#0891b2,color:#fff
    classDef external fill:#ec4899,stroke:#be185d,color:#fff

    class U1,U2,U3,U4 users
    class CF,KV,CDN edge
    class ASTRO,VUE,API app
    class AUTH,PAY,MSG,MEDIA,SAFETY services
    class DB,STOR,FUNC,RT backend
    class STRIPE,GROQ,SUMSUB external`
    },
    {
      title: 'User Roles & Permissions',
      description: 'Permission hierarchy from SuperAdmin down to regular users.',
      code: `flowchart TD
    subgraph Hierarchy["Permission Hierarchy"]
        SA["SuperAdmin"]
        A["Admin"]
        AO["Agency Owner"]
        AE["Agency Employee"]
        C["Creator"]
        U["User/Fan"]
    end

    SA --> A --> AO --> AE
    SA --> A --> C --> U
    AO --> C

    subgraph Permissions["Key Permissions"]
        P1["canManageUsers"]
        P2["canManageSupportTickets"]
        P3["canAccessStripeIntegration"]
        P4["managedCreatorIds[]"]
        P5["employeeCreatorIds[]"]
    end

    classDef super fill:#ef4444,stroke:#b91c1c,color:#fff
    classDef admin fill:#f97316,stroke:#c2410c,color:#fff
    classDef agency fill:#6366f1,stroke:#4f46e5,color:#fff
    classDef creator fill:#22c55e,stroke:#15803d,color:#fff
    classDef user fill:#3b82f6,stroke:#1d4ed8,color:#fff
    classDef perm fill:#1a1a24,stroke:#27272a,color:#a1a1aa

    class SA super
    class A admin
    class AO,AE agency
    class C creator
    class U user
    class P1,P2,P3,P4,P5 perm`
    },
    {
      title: 'Deployment Architecture',
      description: 'Build pipeline from source to global edge deployment.',
      code: `flowchart LR
    subgraph Build["Build Pipeline"]
        A["Source Code"] --> B["Astro Build"]
        B --> C["Vite Bundle"]
        C --> D["Cloudflare Adapter"]
    end

    subgraph Deploy["Cloudflare"]
        E["Workers"]
        F["KV"]
        G["CDN"]
    end

    subgraph Backend["NYC Region"]
        H["Appwrite Cloud"]
    end

    D --> E
    D --> G
    E --> F
    E --> H

    classDef build fill:#6366f1,stroke:#4f46e5,color:#fff
    classDef deploy fill:#f97316,stroke:#c2410c,color:#fff
    classDef backend fill:#22c55e,stroke:#15803d,color:#fff

    class A,B,C,D build
    class E,F,G deploy
    class H backend`
    }
  ];
}

function generateSecurityAudit(data) {
  return `flowchart TD
    subgraph External["External Attack Surface"]
        A[Login/Signup Forms]
        B[Public API Endpoints]
        C[Media Upload]
        D[Payment Webhooks]
        E[KYC Webhooks]
    end

    subgraph Internal["Internal Attack Surface"]
        F[Session Management]
        G[Permission System]
        H[Star Balance]
        I[Message System]
        J[Admin Functions]
    end

    A --> F
    B --> G
    C --> I
    D --> H
    E --> G

    subgraph Targets["High-Value Targets"]
        K[(User PII)]
        L[(Financial Data)]
        M[(Media Files)]
        N[(Session Tokens)]
    end

    F --> N
    G --> K
    H --> L
    I --> M

    classDef external fill:#ef4444,stroke:#b91c1c,color:#fff
    classDef internal fill:#f97316,stroke:#c2410c,color:#fff
    classDef targets fill:#22c55e,stroke:#15803d,color:#fff

    class A,B,C,D,E external
    class F,G,H,I,J internal
    class K,L,M,N targets`;
}

function generateOnboardingFlow(data) {
  return [
    {
      title: 'Platform Overview',
      description: 'What Staryo does - core features and revenue flow.',
      code: `flowchart LR
    subgraph Users["Platform Users"]
        FAN["👤 Fans"]
        CREATOR["⭐ Creators"]
        AGENCY["🏢 Agencies"]
        ADMIN["👑 Admins"]
    end

    subgraph Core["Core Features"]
        MSG["💬 Messaging"]
        STARS["⭐ Star Currency"]
        GIFTS["🎁 Animated Gifts"]
        REQ["📋 Custom Requests"]
    end

    subgraph Revenue["Revenue Flow"]
        BUY["💳 Buy Stars"]
        SPEND["💸 Spend Stars"]
        EARN["💰 Creator Earnings"]
        PAYOUT["🏦 Stripe Payout"]
    end

    FAN --> BUY --> STARS
    FAN --> MSG & GIFTS & REQ
    MSG & GIFTS & REQ --> SPEND
    SPEND --> EARN
    CREATOR --> EARN --> PAYOUT
    AGENCY --> CREATOR
    ADMIN --> Core

    classDef user fill:#3b82f6,stroke:#1d4ed8,color:#fff
    classDef core fill:#6366f1,stroke:#4f46e5,color:#fff
    classDef revenue fill:#22c55e,stroke:#15803d,color:#fff

    class FAN,CREATOR,AGENCY,ADMIN user
    class MSG,STARS,GIFTS,REQ core
    class BUY,SPEND,EARN,PAYOUT revenue`
    },
    {
      title: 'Technology Stack',
      description: 'Frontend, backend, and external service integrations.',
      code: `flowchart TB
    subgraph Frontend["Frontend Layer"]
        ASTRO["Astro 5.16<br/>SSR Framework"]
        VUE["Vue 3.5<br/>UI Components"]
        TW["Tailwind CSS 4<br/>Styling"]
        NS["Nanostores<br/>State Management"]
    end

    subgraph Backend["Backend Layer"]
        AW["Appwrite<br/>BaaS Platform"]
        DB[("Database<br/>NoSQL")]
        STOR[("Storage<br/>Files")]
        FUNC["Functions<br/>Serverless"]
        RT["Realtime<br/>WebSocket"]
    end

    subgraph External["External Services"]
        STRIPE["Stripe<br/>Payments"]
        GROQ["Groq AI<br/>Safety"]
        SUMSUB["SumSub<br/>KYC"]
    end

    subgraph Deploy["Deployment"]
        CF["Cloudflare<br/>Workers + CDN"]
    end

    Frontend --> Deploy --> Backend
    Backend --> External

    classDef frontend fill:#3b82f6,stroke:#1d4ed8,color:#fff
    classDef backend fill:#6366f1,stroke:#4f46e5,color:#fff
    classDef external fill:#22c55e,stroke:#15803d,color:#fff
    classDef deploy fill:#f97316,stroke:#c2410c,color:#fff

    class ASTRO,VUE,TW,NS frontend
    class AW,DB,STOR,FUNC,RT backend
    class STRIPE,GROQ,SUMSUB external
    class CF deploy`
    },
    {
      title: 'Request Lifecycle',
      description: 'How requests flow from browser through edge to backend.',
      code: `sequenceDiagram
    participant B as Browser
    participant CF as Cloudflare Edge
    participant A as Astro SSR
    participant API as API Route
    participant S as Service Layer
    participant AW as Appwrite

    B->>CF: HTTPS Request
    CF->>A: Route to Worker

    alt Static Page
        A->>B: Return HTML
    else API Call
        A->>API: /api/xxx.json
        API->>S: Business Logic
        S->>AW: Database/Storage
        AW->>S: Response
        S->>API: Result
        API->>B: JSON Response
    else Vue Island
        A->>B: HTML + Hydration Script
        B->>B: Vue Hydration
    end`
    },
    {
      title: 'Star Currency System',
      description: 'How virtual currency flows through the platform.',
      code: `flowchart LR
    subgraph Purchase["Star Purchase"]
        USD["$USD"] --> STRIPE["Stripe Checkout"]
        STRIPE --> STARS["⭐ Stars"]
    end

    subgraph Spend["Star Spending"]
        STARS --> MSG["💬 Messages"]
        STARS --> GIFT["🎁 Gifts"]
        STARS --> REQ["📋 Requests"]
    end

    subgraph Earn["Creator Earnings"]
        MSG --> CREATOR["Creator Balance"]
        GIFT --> CREATOR
        REQ --> CREATOR
        CREATOR --> PAYOUT["💰 Stripe Payout"]
    end

    classDef purchase fill:#22c55e,stroke:#15803d,color:#fff
    classDef spend fill:#6366f1,stroke:#4f46e5,color:#fff
    classDef earn fill:#f97316,stroke:#c2410c,color:#fff

    class USD,STRIPE,STARS purchase
    class MSG,GIFT,REQ spend
    class CREATOR,PAYOUT earn`
    },
    {
      title: 'Content Safety System',
      description: 'AI-powered content moderation pipeline.',
      code: `flowchart TD
    subgraph Input["Content Input"]
        TXT["📝 Text"]
        IMG["🖼️ Image"]
        VID["🎬 Video"]
        AUD["🎤 Audio"]
    end

    subgraph Process["Safety Processing"]
        HASH["Generate Hash"]
        CACHE{"Cache<br/>Lookup"}
        AI["Groq LlamaGuard 4"]
        STORE["Store Result"]
    end

    subgraph Output["Result"]
        SAFE["✅ Safe"]
        UNSAFE["❌ Unsafe"]
        AUDIT["📋 Audit Log"]
    end

    TXT & IMG & VID & AUD --> HASH
    HASH --> CACHE
    CACHE -->|Hit| SAFE
    CACHE -->|Miss| AI
    AI --> STORE --> SAFE & UNSAFE
    SAFE & UNSAFE --> AUDIT

    classDef input fill:#3b82f6,stroke:#1d4ed8,color:#fff
    classDef process fill:#6366f1,stroke:#4f46e5,color:#fff
    classDef safe fill:#22c55e,stroke:#15803d,color:#fff
    classDef unsafe fill:#ef4444,stroke:#b91c1c,color:#fff

    class TXT,IMG,VID,AUD input
    class HASH,CACHE,AI,STORE process
    class SAFE,AUDIT safe
    class UNSAFE unsafe`
    },
    {
      title: 'Messaging Flow',
      description: 'End-to-end message sending with safety checks and payments.',
      code: `sequenceDiagram
    participant U as User
    participant API as /api/messages/send
    participant Safety as SafetyService
    participant Pay as PaymentService
    participant DB as Appwrite DB
    participant RT as Realtime

    U->>API: Send Message
    API->>Safety: Check Content

    alt Content Unsafe
        Safety-->>API: Block
        API-->>U: Error: Content Blocked
    else Content Safe
        Safety-->>API: Approved
        API->>Pay: Process Payment

        alt Insufficient Stars
            Pay-->>API: Insufficient Balance
            API-->>U: Error: Buy More Stars
        else Payment OK
            Pay-->>API: Stars Deducted
            API->>DB: Create Message
            DB->>RT: Broadcast Event
            RT->>U: Real-time Update
            API-->>U: Success
        end
    end`
    }
  ];
}

// ============ HELPER FUNCTIONS ============

function getFlowDescription(flowId) {
  const descriptions = {
    auth: 'How users authenticate, manage sessions, and verify identity with 2FA.',
    payment: 'Star purchases, Stripe checkout, and creator payout flows.',
    data: 'Message creation, content moderation, and data persistence.',
    storage: 'File uploads, media processing, and storage bucket organization.',
    api: 'Overview of all API endpoints grouped by functionality.',
    deployment: 'Build pipeline, Cloudflare Workers deployment, and infrastructure.',
    architecture: 'System architecture, user roles, and service layers.',
    security: 'Security audit attack surface analysis and high-value targets.',
    onboarding: 'New developer guide with platform overview and key concepts.'
  };
  return descriptions[flowId] || 'Data flow diagram';
}

function getDetailedDescription(flowId) {
  const descriptions = {
    auth: 'Authentication uses Appwrite SDK for session management. Tokens are stored in both HttpOnly cookies (a_session_xxx) and localStorage for redundancy. 2FA uses Appwrite\'s built-in TOTP/Email/Phone verification. SumSub handles age verification for creators via their WebSDK.',
    payment: 'Stripe Embedded Checkout handles payment UI. Webhooks verify signatures via stripe.webhooks.constructEvent(). Stars are credited via StarBalanceService using FIFO deduction. Creators get paid through Stripe Connect Express accounts.',
    data: 'Messages flow through SafetyService which uses Groq LlamaGuard 4 for text, Groq Whisper for audio transcription, and pHash + Groq Vision for images/video. Payment uses StarBalanceService. Real-time delivery uses Appwrite Realtime WebSockets.',
    storage: 'HEIC images are converted via heic-convert. Thumbnails use Canvas API. pHash generates perceptual hashes via MediaProcessorClient. Appwrite Storage provides AES-256 encryption, ClamAV antivirus, and gzip compression. Per-user buckets ensure privacy.',
    api: 'All APIs use Astro endpoints (.json.ts files). Backend services: Appwrite Cloud (NYC), Stripe API, Groq API (LlamaGuard + Whisper), SumSub API. Processing tools: pHash, Canvas API, heic-convert, FFmpeg.wasm (planned).',
    deployment: 'Astro builds to Cloudflare Workers via @astrojs/cloudflare adapter. Static assets served from Cloudflare CDN. Sessions stored in Cloudflare KV. Secrets managed via Cloudflare Workers Environment. Backend services on Appwrite Cloud (NYC region).',
    architecture: 'Staryo is a creator economy platform enabling monetized messaging via virtual currency (Stars). ~91,000 lines Vue, 153+ API endpoints. Hybrid SSR/SPA on Cloudflare Workers with Appwrite backend.',
    security: 'Attack surface analysis for security auditors. Priority areas: session/auth (XSS risks), payment security (webhook verification), content security (user input handling), authorization (agency boundaries).',
    onboarding: 'Complete developer onboarding guide covering quick start, system overview, architecture deep dive, key concepts (Stars, permissions, safety), codebase navigation, and common workflows.'
  };
  return descriptions[flowId] || 'Interactive diagram showing data flow.';
}

function getLegendItems(flowId) {
  const legends = {
    auth: `
      <div class="legend-item"><div class="legend-color" style="background:#3b82f6"></div>Client (Vue)</div>
      <div class="legend-item"><div class="legend-color" style="background:#6366f1"></div>Appwrite Auth SDK</div>
      <div class="legend-item"><div class="legend-color" style="background:#22c55e"></div>Session Storage</div>
      <div class="legend-item"><div class="legend-color" style="background:#f97316"></div>Appwrite 2FA</div>
      <div class="legend-item"><div class="legend-color" style="background:#ec4899"></div>SumSub KYC</div>
      <div class="legend-item"><div class="legend-color" style="background:#ef4444"></div>Error</div>
    `,
    payment: `
      <div class="legend-item"><div class="legend-color" style="background:#3b82f6"></div>Vue Components</div>
      <div class="legend-item"><div class="legend-color" style="background:#6366f1"></div>Astro API Routes</div>
      <div class="legend-item"><div class="legend-color" style="background:#635bff"></div>Stripe SDK</div>
      <div class="legend-item"><div class="legend-color" style="background:#22c55e"></div>StarBalanceService</div>
      <div class="legend-item"><div class="legend-color" style="background:#f97316"></div>Stripe Connect</div>
      <div class="legend-item"><div class="legend-color" style="background:#27272a"></div>Appwrite DB</div>
    `,
    data: `
      <div class="legend-item"><div class="legend-color" style="background:#3b82f6"></div>Vue Components</div>
      <div class="legend-item"><div class="legend-color" style="background:#f97316"></div>SafetyService + Groq</div>
      <div class="legend-item"><div class="legend-color" style="background:#6366f1"></div>PaymentService</div>
      <div class="legend-item"><div class="legend-color" style="background:#22c55e"></div>Appwrite Collections</div>
      <div class="legend-item"><div class="legend-color" style="background:#06b6d4"></div>Appwrite Realtime</div>
    `,
    storage: `
      <div class="legend-item"><div class="legend-color" style="background:#3b82f6"></div>heic-convert + API</div>
      <div class="legend-item"><div class="legend-color" style="background:#6366f1"></div>pHash + Groq + Canvas</div>
      <div class="legend-item"><div class="legend-color" style="background:#22c55e"></div>Appwrite Buckets</div>
      <div class="legend-item"><div class="legend-color" style="background:#f97316"></div>AES-256 + ClamAV</div>
      <div class="legend-item"><div class="legend-color" style="background:#06b6d4"></div>Appwrite SDK</div>
      <div class="legend-item"><div class="legend-color" style="background:#ec4899"></div>Cloudflare CDN</div>
    `,
    api: `
      <div class="legend-item"><div class="legend-color" style="background:#6366f1"></div>Appwrite Auth</div>
      <div class="legend-item"><div class="legend-color" style="background:#22c55e"></div>Stripe API</div>
      <div class="legend-item"><div class="legend-color" style="background:#06b6d4"></div>Groq API</div>
      <div class="legend-item"><div class="legend-color" style="background:#f97316"></div>Appwrite Storage</div>
      <div class="legend-item"><div class="legend-color" style="background:#ec4899"></div>SumSub API</div>
      <div class="legend-item"><div class="legend-color" style="background:#1e1e2e"></div>Processing Tools</div>
    `,
    deployment: `
      <div class="legend-item"><div class="legend-color" style="background:#3b82f6"></div>Local Dev</div>
      <div class="legend-item"><div class="legend-color" style="background:#6366f1"></div>Build Process</div>
      <div class="legend-item"><div class="legend-color" style="background:#22c55e"></div>Cloudflare Deploy</div>
      <div class="legend-item"><div class="legend-color" style="background:#f97316"></div>Production Runtime</div>
      <div class="legend-item"><div class="legend-color" style="background:#06b6d4"></div>Backend Services</div>
      <div class="legend-item"><div class="legend-color" style="background:#ec4899"></div>Monitoring</div>
    `,
    architecture: `
      <div class="legend-item"><div class="legend-color" style="background:#3b82f6"></div>Users</div>
      <div class="legend-item"><div class="legend-color" style="background:#f97316"></div>Cloudflare Edge</div>
      <div class="legend-item"><div class="legend-color" style="background:#6366f1"></div>Application Layer</div>
      <div class="legend-item"><div class="legend-color" style="background:#22c55e"></div>Service Layer</div>
      <div class="legend-item"><div class="legend-color" style="background:#06b6d4"></div>Appwrite Backend</div>
      <div class="legend-item"><div class="legend-color" style="background:#ec4899"></div>External APIs</div>
    `,
    security: `
      <div class="legend-item"><div class="legend-color" style="background:#ef4444"></div>External Attack Surface</div>
      <div class="legend-item"><div class="legend-color" style="background:#f97316"></div>Internal Attack Surface</div>
      <div class="legend-item"><div class="legend-color" style="background:#22c55e"></div>High-Value Targets</div>
    `,
    onboarding: `
      <div class="legend-item"><div class="legend-color" style="background:#3b82f6"></div>Users/Input</div>
      <div class="legend-item"><div class="legend-color" style="background:#6366f1"></div>Core Features</div>
      <div class="legend-item"><div class="legend-color" style="background:#22c55e"></div>Revenue/Output</div>
      <div class="legend-item"><div class="legend-color" style="background:#f97316"></div>Processing</div>
      <div class="legend-item"><div class="legend-color" style="background:#ef4444"></div>Errors/Unsafe</div>
    `
  };
  return legends[flowId] || '';
}

function truncate(str, maxLen) {
  if (!str) return '';
  if (str.length <= maxLen) return str;
  return str.slice(0, maxLen - 2) + '..';
}

function escapeHtml(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

module.exports = { generateMermaidFlows };
